version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: hhp-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=application
      - MYSQL_PASSWORD=application
      - MYSQL_DATABASE=hhplus
    volumes:
      - ./data/mysql/:/var/lib/mysql
  kafka:
    image: confluentinc/cp-kafka:7.8.1
    container_name: hhp-kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CLUSTER_ID: "pIhRN-FbRSyqSYFiSDtckA"
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
    volumes:
      - "./data/kafka:/var/lib/kafka/data"
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: hhp-kafka-ui
    ports:
      - "8989:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=kafka-cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=hhp-kafka:9092
      - DYNAMIC_CONFIG_ENABLED=true

networks:
  default:
    driver: bridge
